version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: ms_auth
    environment:
      POSTGRES_USER: ms_auth
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ms_auth
    ports:
      - "5431:5432"
    volumes:
      - pgdata:/var/lib/postgresql/18/docker

volumes:
  pgdata:
